### ISSUE TITLE
This package is hard to find

### ISSUE THREAD

**Issue by sjakobi** [Lysxia/generic-random#21]
[Google search results for "haskell generic arbitrary"](https://www.google.com/search?q=haskell%20generic%20arbitrary) don't show generic-random anywhere on the first page. Only on the second page, it is mentioned in some blog posts.

I think it might help to use the term `Arbitrary` in the package description.

And maybe the maintainers for [`generic-arbitrary`](https://hackage.haskell.org/package/generic-arbitrary) could add a reference to this package?

**Comment by Lysxia** [comment]
Yes, that's a problem!

I added some mentions of Arbitrary in the cabal file.

I'll make a release tomorrow, unless another idea to improve things comes up.

**Comment by sjakobi** [comment]
> I added some mentions of Arbitrary in the cabal file.

Many thanks! :)

Feel free to close this issue or let's maybe wait and see whether the Google ranking improves.

**Comment by Lysxia** [comment]
Yeah, let's wait to see some signs of improvements before closing :)

**Comment by Lysxia** [comment]
generic-random now ranks 4th on google (for me, with all the caveats that implies...). I suppose that's good enough for those who know what they're looking for. How high does it rank on your side?

**Comment by sjakobi** [comment]
It's the 5th result for me now, after results for `generic-arbitrary`, `QuickCheck`, `basic-sop` and `regular-extras`. So there's still room for improvement IMHO, but it's already much better than it was.

Thanks! :)
