### ISSUE TITLE
Add link to Brent Yorgey's blogpost

### ISSUE THREAD

**Issue by tom-bop** [Lysxia/generic-random#7]
The documentation in the readme is a bit sparse, and Brent Yorgey has done a nice job writing up an overview (https://byorgey.wordpress.com/2016/09/20/the-generic-random-library-part-1-simple-generic-arbitrary-instances/) - maybe you could link to it?

**Comment by Lysxia** [comment]
Hi, indeed the docs need a lot of work. I am reticent to add it because the API has changed since Brent's post, in particular to check the list of weights at compile time. I just haven't thought about what we can do about this discrepancy yet.

**Comment by Lysxia** [comment]
Here we go. https://hackage.haskell.org/package/generic-random-1.0.0.0
