### ISSUE TITLE
Add `GA` instances for base types?

### ISSUE THREAD

**Issue by byorgey** [Lysxia/generic-random#8]
In trying to update my blog post (see #7), I came across the following problem.  Consider the following minimal example.

```
{-# LANGUAGE DeriveGeneric        #-}
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE GADTSyntax           #-}
{-# LANGUAGE UndecidableInstances #-}

import GHC.Generics
import Test.QuickCheck
import Generic.Random.Generic

data Tree a where
  Leaf   :: a                -> Tree a
  Branch :: Tree a -> Tree a -> Tree a
  deriving (Show, Generic)

instance (Arbitrary a, Generic a, ListBaseCases Z (Rep a)) => Arbitrary (Tree a) where
  arbitrary = genericArbitrary' (S Z) uniform
```
This is fine as far as it goes.  The problem comes when I try to use it:
```
> sample (arbitrary :: Gen (Tree Int))

<interactive>:11:9: error:
    • No instance for (Generic Int) arising from a use of ‘arbitrary’
    • In the first argument of ‘sample’, namely
        ‘(arbitrary :: Gen (Tree Int))’
      In the expression: sample (arbitrary :: Gen (Tree Int))
      In an equation for ‘it’: it = sample (arbitrary :: Gen (Tree Int))
```
The problem seems to be that instances of `Generic` for base types such as `Int` were removed in GHC 8.  See the discussion on https://ghc.haskell.org/trac/ghc/ticket/10512 and https://ghc.haskell.org/trac/ghc/ticket/9526 .  I think (but am not 100% sure) that the proper solution is to add instances of `GA` for base types.  Well, maybe that wouldn't kind check, perhaps there needs to be some sort of `GA0` class?  I'm really not sure exactly what it would look like, but the implication from the discussion on the tickets linked above is that each use of generics needs to somehow define its own ad-hoc behavior for base types, since it does not make sense to have `Generic` instances for them.

**Comment by Lysxia** [comment]
The `Generic` constraint comes with `ListBaseCase`, which computes a set of simple values to end recursion when the size reaches 0. I'll rewrite it to work with non-generic types.

**Comment by Lysxia** [comment]
So I'm almost done with a new version of the base case system.

An `Arbitrary` instance for `Tree` would now look like this:

    instance (Arbitrary a, BaseCase a) => Arbitrary (Tree a) where
      arbitrary = genericArbitraryRec uniform `withBaseCase` (Leaf <$> baseCase)

where `genericArbitraryRec` recursively decreases the size parameter, and the base case at size 0 is explicitly given (here deferring leaf generation to the `BaseCase` type class).

For a 100% push-button solution, base case generation can be derived. An automatic tool has to make some arbitrary choices; if you don't touch anything, a "base case" is any value with minimal depth.

    -- No more depth parameter, all automatic.
    -- Note BaseCase (Tree a), with FlexibleContexts and UndecidableInstances.
    instance (Arbitrary a, BaseCase (Tree a)) => Arbitrary (Tree a) where
      arbitrary = genericArbitrary' uniform

    type instance Found (Tree a) d = GFound (Tree a) d
    instance GBaseCaseSearch (Tree a) d e => BaseCaseSearch (Tree a) d e

Since not all types are `Generic`, some extra magic incantations are required for those that are. Now that I write this, I think I can avoid imposing the last two lines of boilerplate on users. The rest of the API  is pretty stable now.

**Comment by Lysxia** [comment]
This now works on 1.0.0.0!

```haskell
{-# LANGUAGE DeriveGeneric        #-}
{-# LANGUAGE GADTSyntax           #-}

import GHC.Generics
import Test.QuickCheck
import Generic.Random

data Tree a where
  Leaf   :: a                -> Tree a
  Branch :: Tree a -> Tree a -> Tree a
  deriving (Show, Generic)

instance (Arbitrary a, BaseCase a) => Arbitrary (Tree a) where
  arbitrary = genericArbitraryRec uniform `withBaseCase` (Leaf <$> baseCase)

main = sample (arbitrary :: Gen (Tree ()))
```
